FROM python:3.9-slim-buster

# 安装OpenVPN
RUN apt-get update && apt-get install -y openvpn

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["python", "app.py"]