FROM python:3.9-slim-buster

# 安装OpenVPN
RUN apt-get update && apt-get install -y openvpn openresolv

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY src/ .

HEALTHCHECK --interval=5s \
            --timeout=1s \
            --start-period=3s \
            CMD test -e /app/ok || exit 1

CMD ["python", "app.py"]